version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning 
    container_name: redis_backend
    volumes: 
      - cache:/data
  api:
    depends_on:      
      - cache    
    build: .
    container_name: "redis_proxy_cache"
    expose:
      - 8000
    command: 
    - /bin/bash
    - -c
    - |
      python3 -m unittest discover -s ./tests/ -p '*_test.py' -b
      uvicorn src.main:app --host $PROXY_HOST --port $PROXY_PORT
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    environment:
      - CACHE_SIZE=3
      - CACHE_EXPIRY=20
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - REDIS_POLLSIZE=1
      - PROXY_HOST='0.0.0.0'
      - PROXY_PORT=8000
    links:      
      - cache
volumes:
  cache:
    driver: local