version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
  api:
    container_name: redis-cache-proxy
    build: .
    command: uvicorn src.main:app --host 0.0.0.0
    image: redis-cache-proxy
    depends_on:
      - cache
    ports:
      - 8000:8000
    environment:
      ENVIRONMENT: dev     
      REDIS.REDIS_HOST: cache
      REDIS.REDIS_PORT: 6379
      PROXY.HOST: 127.0.0.1
      PROXY.PORT: 8000
      CACHE.SIZE: 3
      CACHE.EXPIRY: 20 
    links:
      - cache
    volumes:
      - ./:/src
volumes:
  cache:
    driver: local